test: DeploymentTest
Add image prefetch due to initializationError observed in ci

orchestratormanager.OrchestratorManagerException: The deployment did not start or reach replica ready state - if this job uses image prefetch check that this image is in the jobs prefetch list e.g. qa-tests-backend/scripts/images-to-prefetch.txt - quay.io/rhacs-eng/qa-multi-arch:nginx-3.21-1